version: '2.2'
services:
    discovery-service:
        container_name: discovery-service
        build:
            context: .
            dockerfile: Dockerfile-discovery-service
        image: discovery-service:latest
        expose:
            - 8761
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
        logging:
            driver: json-file
    account-service:
        container_name: account-service
        build:
            context: .
            dockerfile: Dockerfile-account-service
        image: account-service:latest
        entrypoint: /opt/lib/account-service-entrypoint.sh             
        expose:
            - 2222
        ports:
            - 2222:2222
        networks:
            - spring-cloud-network
        links:
            - discovery-service:discovery-service
        depends_on:
            - discovery-service
        logging:
            driver: json-file
    customer-service:
        container_name: customer-service
        build:
            context: .
            dockerfile: Dockerfile-customer-service
        image: customer-service:latest
        entrypoint: /opt/lib/customer-service-entrypoint.sh
        expose:
            - 3333
        ports:
            - 3333:3333
        networks:
            - spring-cloud-network
        links:
            - discovery-service:discovery-service
            - account-service:account-service
        depends_on:
            - discovery-service
            - account-service
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: .
            dockerfile: Dockerfile-gateway-service
        image: gateway-service:latest
        entrypoint: /opt/lib/gateway-service-entrypoint.sh
        expose:
            - 8765
        ports:
            - 8765:8765
        networks:
            - spring-cloud-network
        links:
            - discovery-service:discovery-service
            - account-service:account-service
            - customer-service:customer-service
        depends_on:
            - discovery-service
            - account-service
            - customer-service
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true