# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
copy account-service-0.0.1-SNAPSHOT.jar /opt/lib/

COPY account-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/account-service-entrypoint.sh

# Make port 8090 available to the world outside this container
EXPOSE 2222

# Add a volume pointing to /var/lib/account-repo
VOLUME /var/lib/account-repo