# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
COPY discovery-service-0.0.1-SNAPSHOT.jar /opt/lib/

COPY discovery-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/discovery-service-entrypoint.sh

# Make port 8761 available to the world outside this container
EXPOSE 8761

# Run the jar file 
ENTRYPOINT ["java","-jar","/opt/lib/discovery-service-0.0.1-SNAPSHOT.jar"]

# Add a volume pointing to /var/lib/discovery-repo
VOLUME /var/lib/discovery-repo


